In [3]:
import numpy as np
import pandas as pd 


In [2]:
print(pd.__version__)
print(pd.show_versions(as_json=True))

1.1.3
{'system': {'commit': 'db08276bc116c438d3fdee492026f8223584c477', 'python': '3.8.5.final.0', 'python-bits': 64, 'OS': 'Windows', 'OS-release': '10', 'Version': '10.0.22000', 'machine': 'AMD64', 'processor': 'AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD', 'byteorder': 'little', 'LC_ALL': None, 'LANG': None, 'LOCALE': {'language-code': 'English_India', 'encoding': '1252'}}, 'dependencies': {'pandas': '1.1.3', 'numpy': '1.21.2', 'pytz': '2020.1', 'dateutil': '2.8.1', 'pip': '20.2.4', 'setuptools': '50.3.1.post20201107', 'Cython': '0.29.21', 'pytest': '6.1.1', 'hypothesis': None, 'sphinx': '3.2.1', 'blosc': None, 'feather': None, 'xlsxwriter': '1.3.7', 'lxml.etree': '4.6.1', 'html5lib': '1.1', 'pymysql': '1.0.2', 'psycopg2': None, 'jinja2': '2.11.2', 'IPython': '7.19.0', 'pandas_datareader': None, 'bs4': '4.9.3', 'bottleneck': '1.3.2', 'fsspec': '0.8.3', 'fastparquet': None, 'gcsfs': None, 'matplotlib': '3.3.2', 'numexpr': '2.7.1', 'odfpy': None, 'openpyxl': '3.0.5', 'pandas_gbq

## Make series

In [28]:
import numpy as np 
mylist = list('abcdefghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist,myarr))
ser = pd.Series(mydict)
ser

a     0
b     1
c     2
d     3
e     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

## series to dataframe

In [13]:
# solution convert series to dataframe us to_frame fucntion
df = ser.to_frame().reset_index()
df.head()


index  0
0     a  0
1     b  1
2     c  2
3     d  3
4     e  4

In [18]:
# assign name to series
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
ser.name='letters'
ser.head()

0    a
1    b
2    c
3    d
4    e
Name: letters, dtype: object

## Get item from series

In [6]:
# get items of series A not present in series B
ser1 = pd.Series([1,2,3,4,5])
ser2= pd.Series([4,5,6,7,8])
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

In [7]:
# get items not common to both series
# uion
ser_u=pd.Series(np.union1d(ser1,ser2))
ser_u


0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [33]:
~ser1.isin(ser2)

0     True
1     True
2     True
3    False
4    False
dtype: bool

In [10]:
ser=pd.Series(np.random.random(20)) # random float total 20 in range 0 to 1


In [11]:
np.random.randint(1,10,20) # this give random number between 1 to 10 of total 20

array([4, 1, 4, 2, 2, 1, 1, 4, 8, 8, 9, 7, 2, 7, 8, 6, 3, 1, 9, 7])

## combine series

In [30]:
# combine series 
serA=pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
serB = pd.Series(np.arange(26))
pd.concat([serA,serB],axis=1)

0   1
0   a   0
1   b   1
2   c   2
3   d   3
4   e   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25

In [27]:
# to datafrmae
pd.DataFrame({'letters':serA,'index':serB})

letters  index
0        a      0
1        b      1
2        c      2
3        d      3
4        e      4
5        f      5
6        g      6
7        h      7
8        i      8
9        j      9
10       k     10
11       l     11
12       m     12
13       n     13
14       o     14
15       p     15
16       q     16
17       r     17
18       s     18
19       t     19
20       u     20
21       v     21
22       w     22
23       x     23
24       y     24
25       z     25

## Get minimum,25th percentile,median,75th and max of numeric series

In [42]:
ser = pd.Series(np.random.normal(10,5,25))

In [46]:
np.percentile(ser,[0,25,50,75,100])

array([ 2.07172127,  5.82393317,  8.28732544, 10.3324764 , 20.95435771])

## Unique value in series

In [59]:
ser=pd.Series(np.random.randint(91,100,25))

In [61]:
ser.value_counts()

94    7
95    4
93    3
99    3
97    3
92    2
91    1
98    1
96    1
dtype: int64

In [68]:
ser[~ser.isin(ser.value_counts().index[:2])]='other'

In [69]:
ser

0     other
1     other
2     other
3        94
4        94
5     other
6     other
7        94
8     other
9        94
10    other
11    other
12       94
13    other
14    other
15    other
16       95
17       95
18       94
19       94
20       95
21    other
22    other
23    other
24       95
dtype: object

## bin a numeric seriws to 10 groups

In [71]:
ser=pd.Series(np.random.random(20))

In [76]:
# use qcut
pd.qcut(ser,q=[0,0.1,.2,.3,.4,.5,.6,.7,.8,.9,1],
       labels=['1st','2nd','3rd','4th','5th','6th','7th','8th','9th','10th'])

0      6th
1      1st
2     10th
3     10th
4      1st
5      5th
6      2nd
7      9th
8      9th
9      3rd
10     4th
11     3rd
12     8th
13     7th
14     2nd
15     6th
16     4th
17     8th
18     5th
19     7th
dtype: category
Categories (10, object): ['1st' < '2nd' < '3rd' < '4th' ... '7th' < '8th' < '9th' < '10th']

## convert numpyarray to dataframe

In [97]:
ser = pd.Series(np.random.randint(1,10,35))
ser

0     1
1     6
2     2
3     6
4     3
5     7
6     4
7     8
8     1
9     8
10    2
11    8
12    2
13    1
14    4
15    6
16    4
17    7
18    7
19    5
20    7
21    3
22    6
23    4
24    8
25    3
26    6
27    9
28    3
29    9
30    6
31    5
32    6
33    1
34    1
dtype: int32

In [83]:
pd.DataFrame(ser,columns=['num'])

num
0     9
1     6
2     7
3     7
4     5
5     2
6     1
7     6
8     2
9     9
10    4
11    8
12    7
13    3
14    1
15    1
16    4
17    1
18    9
19    7
20    2
21    2
22    7
23    3
24    3
25    2
26    3
27    4
28    6
29    1
30    2
31    5
32    3
33    9
34    6

In [93]:
pd.DataFrame(ser.values.reshape(7,5))

0  1  2  3  4
0  9  6  7  7  5
1  2  1  6  2  9
2  4  8  7  3  1
3  1  4  1  9  7
4  2  2  7  3  3
5  2  3  4  6  1
6  2  5  3  9  6

In [89]:
ser.values.reshape(1,35)

array([[9, 6, 7, 7, 5, 2, 1, 6, 2, 9, 4, 8, 7, 3, 1, 1, 4, 1, 9, 7, 2, 2,
        7, 3, 3, 2, 3, 4, 6, 1, 2, 5, 3, 9, 6]])

## find values from series multiple of 3

In [117]:
ser = pd.Series(np.random.randint(1,10,12))

In [118]:
ser[ser%3==0]

0    9
6    6
7    9
dtype: int32

In [3]:
#np.argwhere(ser % 3==0)  # not working

In [109]:
## Extracg item at specifict position
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))


In [114]:
ser.take([5,4,25])

5     f
4     e
25    z
dtype: object

## Stack two series vertically and horizontally

In [120]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

In [123]:
# vertical use append
ser1.append(ser2)

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object

In [126]:
# horizontal use concate
pd.concat([ser1,ser2],axis=1)

0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

In [143]:
# 11 Get position of items series one in another series
serA=pd.Series([45,23,13,4,7,65,8,12,6])
serB = pd.Series([4,6,8])

In [144]:
# get index of serB in serA
[pd.Index(serA).get_loc(i) for i in serB]

[3, 8, 6]

In [152]:
# get index
[np.where(i==serA)[0].tolist()[0] for i in serB]

[3, 8, 6]

In [146]:
serA

0    45
1    23
2    13
3     4
4     7
5    65
6     8
7    12
8     6
dtype: int64

## compoute the mean squared error on a truth and predicted series

In [6]:
truth=pd.Series(range(10))
pred = pd.Series(range(10))+ np.random.random(10)

In [11]:
np.mean((truth-pred)**2)

0.38082603181836505

## convert first char of series in upper case

In [16]:
ser = pd.Series(['how','here','avi','read','He'])
ser.str.capitalize()

0     How
1    Here
2     Avi
3    Read
4      He
dtype: object

In [19]:
ser.map(lambda x: x.title())

pandas.core.series.Series

In [ ]:
pd.Series([i.title for i in ser])

In [20]:
# length of ser
ser.map(lambda x: len(x))

0    3
1    4
2    3
3    4
4    2
dtype: int64

In [29]:
## differance of differance between consequtive numbers of a series
ser = pd.Series([1,3,6,10,15,21,27,35])


In [30]:
[ser[i+1]-ser[i] for i in range(len(ser)-1)]

[2, 3, 4, 5, 6, 6, 8]

In [33]:
# 1 difference
ser.diff().to_list()

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]

In [37]:
ser.diff().diff().to_list()

[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]

## datestring series to timeseries

In [41]:
ser=pd.Series(['01 jan 2010','01-01-2011','20120303','2013/04/04','2014-05-05',
           '2015-06-06T12:20'])

In [42]:
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-01-01 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [43]:
from dateutil.parser import parse
ser.map(lambda x: parse(x))

0   2010-01-01 00:00:00
1   2011-01-01 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [66]:
## Get month, week number,day of year and day of week from series
ser = pd.Series(['01 jan 2010','02-02-2011','20120303','2013/04/04','2014-05-05',
           '2015-06-06T12:20'])

In [67]:
# day
pd.to_datetime(ser).dt.day

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [68]:
# month
pd.to_datetime(ser).dt.day_name()



0       Friday
1    Wednesday
2     Saturday
3     Thursday
4       Monday
5     Saturday
dtype: object

## convert year-month string to dates corrsponding 4th day of the month


In [80]:
ser = pd.Series(['Jan 2010','Feb 2011','Mar 2012'])

In [76]:
pd.to_datetime(ser)

0   2010-01-01
1   2011-02-01
2   2012-03-01
dtype: datetime64[ns]

In [78]:
ser

0    Jan 2010
1    Feb 2011
2    Mar 2012
dtype: object

In [84]:
from dateutil.parser import parse 
ser_date=ser.map(lambda x: parse(x))

In [86]:
# construct date string with date as 4
ser_datestr = ser_date.dt.year.astype('str') + '-'+ser_date.dt.month.astype('str')+'-'+'04'

In [88]:
[parse(i).strftime("%Y-%m-%d") for i in ser_datestr]

['2010-01-04', '2011-02-04', '2012-03-04']

In [89]:
ser.map(lambda x: parse('04 '+x))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

## filter words that contain atleast two words

In [90]:
## filter words that contain atlearst two words
ser = pd.Series(['Apple','Orange','Plan','Python','Money'])

In [92]:
from collections import Counter
mask=ser.map(lambda x: sum([Counter(x.lower()).get(i,0) for i in list('aeiou')])>=2)

In [93]:
ser[mask]

0     Apple
1    Orange
4     Money
dtype: object

## filter valid emails from series

In [102]:
emails = pd.Series(['buying books at amazon.com','rameses@egypt.com','matt@t.co','avinash@avi.com'])

In [103]:
pattern = '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

In [104]:
import re 
mask = emails.map(lambda x: bool(re.match(pattern,x)))


In [105]:
emails[mask]

1    rameses@egypt.com
2            matt@t.co
3      avinash@avi.com
dtype: object

In [106]:
# solution 2
emails.str.findall(pattern,flags=re.IGNORECASE)

0                     []
1    [rameses@egypt.com]
2            [matt@t.co]
3      [avinash@avi.com]
dtype: object

In [107]:
## compute euclidean distance between two series
p = pd.Series([1,2,3,4,5,6,7,8,9,10])
q = pd.Series([10,9,8,7,6,5,4,3,2,1])

In [113]:
(np.sum((p-q)**2))**0.5

18.16590212458495

In [114]:
# usgin the formuls
np.linalg.norm(p-q)

18.16590212458495

## find local maxima or peaks

In [115]:
ser = pd.Series([2,10,3,4,9,10,2,7,3])

In [116]:
dd = np.diff(np.sign(np.diff(ser)))
peak_locs = np.where(dd==-2)[0]+1

In [117]:
peak_locs

array([1, 5, 7], dtype=int64)

In [118]:
# replace the string c

# Input
my_str = 'dbc deb abed gade'
# Solution
ser = pd.Series(list('dbc deb abed gade'))
freq = ser.value_counts()
print(freq)
least_freq = freq.dropna().index[-1]
"".join(ser.replace(' ', least_freq))


d    4
     3
e    3
b    3
a    2
c    1
g    1
dtype: int64


'dbcgdebgabedggade'

## create TimeSeries starting '2000-01-01' and 10 weekends

In [119]:
ser = pd.Series(np.random.randint(1,10,10),pd.date_range('2000-01-01',periods=10,freq='W-SAT'))

In [120]:

ser

2000-01-01    1
2000-01-08    3
2000-01-15    9
2000-01-22    9
2000-01-29    6
2000-02-05    5
2000-02-12    7
2000-02-19    8
2000-02-26    7
2000-03-04    8
Freq: W-SAT, dtype: int32

## fill time series so all missing dates show up with values of previous non-missing values

In [4]:
ser = pd.Series([1,10,3,np.nan],index=pd.to_datetime(['2000-01-01','2000-01-03','2000-01-06','2000-01-08']))

In [5]:
ser

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64

In [6]:
# ffill
ser.resample('D').ffill()

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

In [7]:
# bfill
ser.resample("D").bfill()

2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     NaN
2000-01-08     NaN
Freq: D, dtype: float64

In [9]:
ser.resample('D').ffill().bfill()

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

## Compute the autocorrelation of numeric series

In [10]:
## compute the autocorrelation of numeric series
ser = pd.Series(np.arange(20) + np.random.normal(1,10,20))

In [15]:
autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]
autocorrelations[1:]

[0.63, 0.48, 0.65, 0.69, 0.5, 0.48, 0.65, 0.38, 0.12, -0.01]

## import nth row from  a csv file

In [17]:
# Solution 1: Use chunks and for-loop
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)

In [19]:
df2= pd.DataFrame()

In [20]:
for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])

In [21]:
df2

age       b  chas      crim     dis  indus  lstat  medv    nox  \
0     65.2  396.90   0.0   0.00632  4.0900   2.31   4.98  24.0  0.538   
50    45.7  395.56   0.0   0.08873  6.8147   5.64  13.45  19.7  0.439   
100   79.9  394.76   0.0   0.14866  2.7778   8.56   9.42  27.5  0.520   
150   97.3  372.80   0.0   1.65660  1.6180  19.58  14.10  21.5  0.871   
200   13.9  384.30   0.0   0.01778  7.6534   1.47   4.45  32.9  0.403   
250   13.0  396.28   0.0   0.14030  7.3967   5.86   5.90  24.4  0.431   
300   47.4  390.86   0.0   0.04417  7.8278   2.24   6.07  24.8  0.400   
350   44.4  396.90   0.0   0.06211  8.7921   1.25   5.98  22.9  0.429   
400  100.0  396.90   0.0  25.04610  1.5888  18.10  26.77   5.6  0.693   
450   92.6    0.32   0.0   6.71772  2.3236  18.10  17.44  13.4  0.713   
500   79.7  396.90   0.0   0.22438  2.4982   9.69  14.33  16.8  0.585   

     ptratio   rad     rm    tax    zn  
0       15.3   1.0  6.575  296.0  18.0  
50      16.8   4.0  5.963  243.0  21.0  
100     20.9   5.0  6.727  384.0   0.0  
150     14.7   5.0  6.122  403.0   0.0  
200     17.0   3.0  7.135  402.0  95.0  
250     19.1   7.0  6.487  330.0  22.0  
300     14.8   5.0  6.871  358.0  70.0  
350     19.7   1.0  6.490  335.0  40.0  
400     20.2  24.0  5.987  666.0   0.0  
450     20.2  24.0  6.749  666.0   0.0  
500     19.2   6.0  6.027  391.0   0.0

In [ ]:
# Solution2 